import Head from "next/head";
import { useId } from "react";
import { Form } from "react-aria-components";
import { ArticleRenderer } from "@/components/article-renderer";
import { AvatarButton } from "@/components/ui/avatar/Avatar";
import { Button } from "@/components/ui/button";
import { Checkbox, CheckboxGroup } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogActions,
  DialogBody,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Menu, MenuItem, MenuTrigger } from "@/components/ui/menu";
import { Radio, RadioGroup } from "@/components/ui/radio";
import { Select, SelectItem } from "@/components/ui/select";
import { Text } from "@/components/ui/text";
import { TextField } from "@/components/ui/text-field";
import styles from "./index.module.scss";

export default function Home() {
  const formId = useId();

  return (
    <>
      <Head>
        <title>Brevity Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.container}>
          <DialogTrigger>
            <Button>Return order</Button>
            <Dialog>
              {({ close }) => (
                <>
                  <DialogTitle>Return Order</DialogTitle>
                  <DialogBody className={styles.dialogBody}>
                    <Text>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Vel eos amet ad! Iste asperiores quibusdam facere
                      voluptatum, nihil excepturi commodi ullam odit dolorem
                      maxime! Minus dignissimos id sit dicta. Autem?
                    </Text>
                    <Form
                      id={formId}
                      onSubmit={(e) => {
                        e.preventDefault();
                        close();
                      }}
                      className={styles.form}
                    >
                      <CheckboxGroup
                        isRequired
                        name="products"
                        label="Select your products"
                      >
                        <Checkbox value="1">iPhone 16</Checkbox>
                        <Checkbox value="2">Samsung Galaxy S25</Checkbox>
                        <Checkbox value="3">Google Pixel 8a</Checkbox>
                      </CheckboxGroup>
                      <RadioGroup
                        isRequired
                        className={styles.mt5}
                        label="Reason"
                        name="reason"
                        description="Select the reason for your return"
                      >
                        <Radio value="1">The product is too expensive</Radio>
                        <Radio value="2">
                          The product is not what I expected
                        </Radio>
                        <Radio value="3">I changed my mind</Radio>
                        <Radio value="4">Other</Radio>
                      </RadioGroup>
                      <Select
                        className={styles.mt5}
                        label="Refund method"
                        description="The purchase amount will be refunded using this method"
                        name="refundMethod"
                        isRequired
                      >
                        <SelectItem>Credit card</SelectItem>
                        <SelectItem>PayPal</SelectItem>
                        <SelectItem>Bank transfer</SelectItem>
                        <SelectItem>Gift card</SelectItem>
                      </Select>
                      <TextField
                        className={styles.mt5}
                        name="comments"
                        label="Comments"
                        placeholder="Additional comments"
                      />
                    </Form>
                  </DialogBody>
                  <DialogActions>
                    <Button variant="tertiary" onPress={close}>
                      Cancel
                    </Button>
                    <Button form={formId} type="submit">
                      Submit
                    </Button>
                  </DialogActions>
                </>
              )}
            </Dialog>
          </DialogTrigger>
          <MenuTrigger>
            <AvatarButton initials="JD" size="md" label={"Open menu"} />
            <Menu>
              <MenuItem href="https://google.com">Item 1</MenuItem>
              <MenuItem>Item 2</MenuItem>
              <MenuItem>Item 3</MenuItem>
            </Menu>
          </MenuTrigger>
          <DialogTrigger>
            <Button variant="secondary">Read terms of service</Button>
            <Dialog>
              {({ close }) => (
                <>
                  <DialogTitle>Terms of Service</DialogTitle>
                  <DialogBody>
                    <ArticleRenderer>
                      <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Vel eos amet ad! Iste asperiores quibusdam facere
                        voluptatum, nihil excepturi commodi ullam odit dolorem
                        maxime! Minus dignissimos id sit dicta. Autem?
                      </p>
                      <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Vel eos amet ad! Iste asperiores quibusdam facere
                        voluptatum, nihil excepturi commodi ullam odit dolorem
                        maxime! Minus dignissimos id sit dicta. Autem?
                      </p>
                      <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Vel eos amet ad! Iste asperiores quibusdam facere
                        voluptatum, nihil excepturi commodi ullam odit dolorem
                        maxime! Minus dignissimos id sit dicta. Autem?
                      </p>
                    </ArticleRenderer>
                  </DialogBody>
                  <DialogActions>
                    <Button onPress={close}>Accept</Button>
                  </DialogActions>
                </>
              )}
            </Dialog>
          </DialogTrigger>
          <Button
            variant="tertiary"
            onPress={() => {
              if (
                document.documentElement.getAttribute("data-mode") === "dark"
              ) {
                document.documentElement.setAttribute("data-mode", "light");
              } else {
                document.documentElement.setAttribute("data-mode", "dark");
              }
            }}
          >
            Toggle dark mode
          </Button>
        </div>
      </main>
    </>
  );
}
