import Head from "next/head";
import { useId } from "react";
import { Form } from "react-aria-components";

import { ArticleRenderer } from "@/components/article-renderer";
import { AvatarButton } from "@/components/avatar/Avatar";
import { Button } from "@/components/button";
import { Checkbox, CheckboxGroup } from "@/components/checkbox";
import {
  Dialog,
  DialogActions,
  DialogBody,
  DialogTitle,
  DialogTrigger,
} from "@/components/dialog";
import { Menu, MenuItem, MenuTrigger } from "@/components/menu";
import { Radio, RadioGroup } from "@/components/radio";
import { Select, SelectItem } from "@/components/select";
import { Text } from "@/components/text";
import { TextField } from "@/components/text-field";
import { spacings } from "@/styles/tokens";

export default function Home() {
  const formId = useId();

  return (
    <>
      <Head>
        <title>Brevity Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          css={{
            display: "flex",
            gap: "16px",
            justifyContent: "center",
            alignItems: "center",
            padding: "32px",
          }}
        >
          <DialogTrigger>
            <Button>Return order</Button>
            <Dialog>
              {({ close }) => (
                <>
                  <DialogTitle>Return Order</DialogTitle>
                  <DialogBody css={{ marginTop: spacings[2] }}>
                    <Text>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Vel eos amet ad! Iste asperiores quibusdam facere
                      voluptatum, nihil excepturi commodi ullam odit dolorem
                      maxime! Minus dignissimos id sit dicta. Autem?
                    </Text>
                    <Form
                      id={formId}
                      onSubmit={(e) => {
                        e.preventDefault();
                        close();
                      }}
                      css={{ marginTop: spacings[6] }}
                    >
                      <CheckboxGroup
                        isRequired
                        name="products"
                        label="Select your products"
                      >
                        <Checkbox value="1">iPhone 16</Checkbox>
                        <Checkbox value="2">Samsung Galaxy S25</Checkbox>
                        <Checkbox value="3">Google Pixel 8a</Checkbox>
                      </CheckboxGroup>
                      <RadioGroup
                        isRequired
                        css={{ marginTop: spacings[5] }}
                        label="Reason"
                        name="reason"
                        description="Select the reason for your return"
                      >
                        <Radio value="1">The product is too expensive</Radio>
                        <Radio value="2">
                          The product is not what I expected
                        </Radio>
                        <Radio value="3">I changed my mind</Radio>
                        <Radio value="4">Other</Radio>
                      </RadioGroup>
                      <Select
                        css={{ marginTop: spacings[5] }}
                        label="Refund method"
                        description="The purchase amount will be refunded using this method"
                        name="refundMethod"
                        isRequired
                      >
                        <SelectItem>Credit card</SelectItem>
                        <SelectItem>PayPal</SelectItem>
                        <SelectItem>Bank transfer</SelectItem>
                        <SelectItem>Gift card</SelectItem>
                      </Select>
                      <TextField
                        css={{ marginTop: spacings[5] }}
                        name="comments"
                        label="Comments"
                        placeholder="Additional comments"
                      />
                    </Form>
                  </DialogBody>
                  <DialogActions>
                    <Button variant="tertiary" onPress={close}>
                      Cancel
                    </Button>
                    <Button form={formId} type="submit">
                      Submit
                    </Button>
                  </DialogActions>
                </>
              )}
            </Dialog>
          </DialogTrigger>
          <MenuTrigger>
            <AvatarButton initials="JD" size="md" label={"Open menu"} />
            <Menu>
              <MenuItem href="https://google.com">Item 1</MenuItem>
              <MenuItem>Item 2</MenuItem>
              <MenuItem>Item 3</MenuItem>
            </Menu>
          </MenuTrigger>
          <DialogTrigger>
            <Button>Read terms of service</Button>
            <Dialog>
              <DialogTitle>Terms of Service</DialogTitle>
              <DialogBody>
                <ArticleRenderer>
                  <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel
                    eos amet ad! Iste asperiores quibusdam facere voluptatum,
                    nihil excepturi commodi ullam odit dolorem maxime! Minus
                    dignissimos id sit dicta. Autem?
                  </p>
                  <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel
                    eos amet ad! Iste asperiores quibusdam facere voluptatum,
                    nihil excepturi commodi ullam odit dolorem maxime! Minus
                    dignissimos id sit dicta. Autem?
                  </p>
                  <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel
                    eos amet ad! Iste asperiores quibusdam facere voluptatum,
                    nihil excepturi commodi ullam odit dolorem maxime! Minus
                    dignissimos id sit dicta. Autem?
                  </p>
                </ArticleRenderer>
              </DialogBody>
              <DialogActions>
                <Button>Accept</Button>
              </DialogActions>
            </Dialog>
          </DialogTrigger>
        </div>
      </main>
    </>
  );
}
