name: "Chromatic"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # https://www.chromatic.com/docs/turbosnap#configure
          onlyChanged: true
